name: simsiam-ucf101-experiment-resnet18_cifar_variant1
dataset: 
  name: ucf101
  image_size: 32
  num_workers: 9
  ordering: 'iid'

model: 
  name: simsiam
  backbone: resnet18_cifar_variant1
  proj_layers: 2

train:
  optimizer: 
    name: sgd
    weight_decay: 0.0005
    momentum: 0.9
  warmup_epochs: 10
  warmup_lr: 0
  base_lr: 0.03
  final_lr: 0
  num_epochs: 3 # this parameter influence the lr decay
  stop_at_epoch: 3 # has to be smaller than num_epochs
  batch_size: 512
  knn_monitor: False # knn monitor will take more time
  knn_interval: 10
  knn_k: 200
eval: # linear evaluation, False will turn off automatic evaluation after training
  optimizer: 
    name: sgd
    weight_decay: 0
    momentum: 0.9
  warmup_lr: 0
  warmup_epochs: 0
  base_lr: 30
  final_lr: 0
  batch_size: 256
  num_epochs: 3
  num_classes: 101

logger:
  tensorboard: True
  matplotlib: True

seed: null # None type for yaml file
# two things might lead to stochastic behavior other than seed:
# worker_init_fn from dataloader and torch.nn.functional.interpolate 
# (keep this in mind if you want to achieve 100% deterministic)




